"""Second-stage forward-jump training configuration for Solo12 v3_1."""

from legged_gym.envs.go1.go1_config import Go1Cfg, Go1CfgPPO
from legged_gym.envs.solo12.solo12_v3_1_common import (
    Solo12V31Asset,
    Solo12V31Control,
    Solo12V31InitState,
    Solo12V31Morphology,
    Solo12V31Viewer,
)


class Solo12V31Cfg(Go1Cfg):
    task_name = "solo12_v3_1_forward"
    init_state = Solo12V31InitState
    morphology = Solo12V31Morphology
    control = Solo12V31Control
    asset = Solo12V31Asset
    viewer = Solo12V31Viewer

    class env(Go1Cfg.env):
        reset_height = 0.12

    class domain_rand(Go1Cfg.domain_rand):
        # Continue from a forward-jump checkpoint while gradually removing the
        # simulator velocity injection. After 400 PPO iterations all horizontal
        # momentum must be generated by the policy during stance.
        push_towards_goal = True
        push_towards_goal_probability = 0.8
        push_towards_goal_final_probability = 0.0
        push_towards_goal_anneal_start_iteration = 1900
        push_towards_goal_anneal_iterations = 400

        class ranges(Go1Cfg.domain_rand.ranges):
            added_mass_range = [-0.5, 1.0]
            com_displacement_range = [-0.04, 0.04]
            added_link_mass_range = [0.8, 1.2]

    class rewards(Go1Cfg.rewards):
        max_contact_force = 160.0


class Solo12V31CfgPPO(Go1CfgPPO):
    class algorithm(Go1CfgPPO.algorithm):
        # A conservative fixed rate avoids destroying the transferred upward
        # jump while the policy adapts to the full forward command envelope.
        learning_rate = 3.e-4
        schedule = "fixed"

    class runner(Go1CfgPPO.runner):
        experiment_name = "test_solo12_v3_1"
